### ISSUE TITLE
How to run this ?

### ISSUE THREAD

**Issue by abhijeet3922** [alions7000/SEC-EDGAR-text#1]
Hi,

This repo seemed promising for my work.
I am not able to run it.
python secedgartext --storage=/tmp/my_storage_folder

There is no secedgartext file to run.

**Comment by alions7000** [comment]
secedgartext is a folder name, not a .py module. It refers to the
containing folder, you should see that in the target location where you
cloned the repo.

You need to run from the folder 'above' that location.

**Comment by VicLana** [comment]
Hi, I am not able to run it either. I was not able to find a folder named 'secedgartext'?

**Comment by alions7000** [comment]
You're right there's a typo on the instructions. Should read SEC-EDGAR-text instead of secedgartext. Thanks for catching that. Let me know if this works for you, then I'll update the readme. Thanks! 

## Installation
Clone the repo, and install the packages in requirements.txt.

    git clone https://github.com/alions7000/SEC-EDGAR-text
    pip install -r SEC-EDGAR-text/requirements.txt

## Usage
Typical usage. This will download the 500 large US companies in the
included 'companies_list.txt' file. Run from the project folder.

    python SEC-EDGAR-text --storage=/tmp/my_storage_folder

**Comment by abhijeet3922** [comment]
This works like a charm. Extraction quality is quite good.
Thanks.

**Comment by VicLana** [comment]
I'm new to Python. I guess everybody knows this...Here is how I installed the package in Anaconda and ran it:
Installation:
1. Download the package
2. Run Anaconda Prompt and cd the directory where requirements.txt locates
3. pip install -r requirements.txt
Use the package:
1. Run Anaconda Prompt
2. cd the directory requirements.txt locates, and cd back to the folder above it
3. python SEC-EDGAR-text-master --storage=the directory of storage folder

Now I can download item1 item1A and item7 of 10-Ks/10-Qs with this package. 
Thanks!!
